SuSang-YuHee/Debate-Ducks-Client

- .gitignore
- pages/debates/create.tsx
- pages/debates/debate/[debateId].tsx
- pages/debates/debateroom/[debateId].tsx
- pages/debates/edit/[debateId].tsx
- pages/debates/index.tsx
> 환경 변수 관련 파일 버전 관리 제외

- components/debateroom/Room.tsx
- pages/debates/debateroom/[debateId].tsx
- debateroom 입장 시 해당 번호의 방으로 입장
- 방에 2인 이상이 있을 경우 입장 거부
> WebSocket 방 입장 기능 추가

- components/debateroom/Buttons.tsx
- components/debateroom/Room.tsx
- components/debateroom/utils/screenShare.ts
- components/debateroom/utils/simple-peer.ts
- components/debateroom/utils/toggleMute.ts
> 오디오 및 비디오의 끄기/켜기 기능과 화면 공유 기능 추가

- components/debateroom/Buttons.tsx
- components/debateroom/Room.tsx
- components/debateroom/types.ts
- components/debateroom/utils/screenShare.ts
- components/debateroom/utils/simple-peer.ts
- pages/debates/debateroom/[debateId].tsx
> WebRTC 재연결 기능 추가

- components/debateroom/Buttons.tsx
- components/debateroom/Room.tsx
- components/debateroom/types.ts
- components/debateroom/utils/toggle.ts
- components/debateroom/utils/webSocket.ts
- 양측 모두 준비버튼을 누르면 토론 시작
- 해당 정보를 서버에 저장해 사용자가 재접속 해도 토론 상태 유지
> 토론 시작 기능 추가

- package-lock.json
- package.json
- pages/signup/index.tsx
- styles/Signup.module.scss
- 회원가입 기능 추가
- 회원가입 유효성 검사 추가
- 회원가입 완료 시 메인 페이지로 이동
> 회원가입 기능 추가

- api/debates.ts
- components/debates/CreateOrEdit.tsx
- components/debates/debate/AfterDebate.tsx
- components/debates/debate/DebaterInfo.tsx
- components/debates/debate/index.tsx
- package-lock.json
- pages/debates/[debateId].tsx
- pages/debates/create.tsx
- pages/debates/edit/[debateId].tsx
- types.ts
- utils/queries/debates.ts
- 수정 후 GET 재요청 방지
- 조회 목록에 팩트체크, 좋아요 수, 투표 추가
- 생성과 수정 모달 메시지 구분
기존: Patch 요청 후 Get 요청
개선: Patch 요청 후 Get 요청 없이 업데이트
> 토론 게시물 CRUD 개선

- pages/signin/index.tsx
> 토큰 저장 기능 추가

- api/users.ts
- pages/_app.tsx
- pages/debates/[debateId].tsx
- pages/signin/index.tsx
- types.ts
- utils/queries/debates.ts
- utils/queries/factchecks.ts
- utils/queries/hearts.ts
- utils/queries/index.ts
- utils/queries/users.ts
- utils/queries/votes.ts
> 유저 정보 조회 리액트 쿼리 적용

- components/debates/debateroom/utils/draw.ts
- styles/globals.scss
- styles/variable.scss
- utils/common/constant.ts
> 색상 변수 공용 설정

- components/common/modal/ConfirmModal.module.scss
- components/common/modal/ConfirmModal.tsx
- components/debates/debates/Filters.module.scss
- components/debates/debates/Filters.tsx
- components/debates/debates/LikeBtn.module.scss
- components/debates/debates/LikeBtn.tsx
- pages/_app.tsx
- pages/_document.tsx
- pages/debates/index.tsx
- styles/variable.scss
> 좋아요 목록만 보기 버튼 및 공용 모달

- pages/mypage/index.tsx
- styles/MyPage.module.scss
> 마이페이지 유저 프로필 조회 및 스타일링 설정

- api/users.ts
- components/common/modal/CheckSignInModal.tsx
- components/common/modal/ConfirmModal.module.scss
- components/common/modal/SignInModal.module.scss
- components/common/modal/SignInModal.tsx
- components/debates/debates/DebatesContainer.tsx
- components/debates/debates/DebatesList.tsx
- components/debates/debates/LikeBtn.tsx
- pages/debates/index.tsx
- styles/variable.scss
- utils/queries/comments.ts
- utils/queries/debates.ts
- utils/queries/factchecks.ts
- utils/queries/hearts.ts
- utils/queries/users.ts
- utils/queries/votes.ts
> 로그인이 필요한 서비스 모달 추가

- api/users.ts
> 병합 과정 괄호 누락 에러 수정

- pages/mypage/index.tsx
> [Update] 유저 프로필 이미지 업로드 기능 추가

- components/debates/CreateOrEdit.module.scss
- components/debates/debate/AfterDebate.tsx
- components/debates/debate/Factcheck.tsx
- components/debates/debate/Factchecks.module.scss
- components/debates/debate/Vote.module.scss
- components/debates/debate/Vote.tsx
- components/debates/debate/index.module.scss
- components/debates/debate/index.tsx
- components/debates/debates/DebateCard.tsx
- components/debates/debates/DebatesCards.module.scss
- utils/common/thousandDigit.ts
> 투표 기능 업데이트 및 스타일 추가

- package-lock.json
- package.json
- pages/mypage/MyPage.module.scss
- pages/mypage/index.tsx
- styles/MyPage.module.scss
> 마이페이지 스타일링

- components/Header.module.scss
- components/Header.tsx
> 로그인 전 프로필 대신 버튼 보이기

- components/debates/DebaterInfo.module.scss
- components/debates/debate/Comments.module.scss
- components/debates/debate/Comments.tsx
- components/debates/debate/Factcheck.tsx
- components/debates/debate/Factchecks.tsx
- components/debates/debate/Vote.module.scss
- components/debates/debate/index.module.scss
- components/debates/debate/index.tsx
- styles/variable.scss
- types.ts
- utils/common/constant.ts
- utils/queries/debates.ts
- utils/queries/factchecks.ts
- utils/queries/hearts.ts
- utils/queries/votes.ts
```ts
onError: (
err: AxiosError<{ message: string }>,
_,
rollback: (() => Debate) | undefined,
) => {
if (rollback) rollback();
toast.error(
`${err.response?.data?.message || "네트워크 에러가 발생했습니다."}`,
);
},
```
> 댓글 기능 개선 및 스타일 작업 & 빌드시 타입 에러 해결

- next.config.js
- package-lock.json
- package.json
- pages/debates/[debateId].tsx
- pages/debates/edit/[debateId].tsx
- pages/mypage/index.tsx
> 빌드 시 발생하는 에러 해결

- package.json
> 빌드 스크립트 변경

- components/Header.module.scss
- components/Header.tsx
> 헤더 프로필 클릭시 마이페이지 및 로그아웃 표시

- api/users.ts
- pages/mypage/MyPage.module.scss
- pages/mypage/index.tsx
- utils/queries/users.ts
> 이미지 변경 Mutation 설정

- components/common/btn/HomeAndTopBtn.module.scss
- components/common/btn/HomeAndTopBtn.tsx
- components/debates/debate/index.tsx
- pages/index.tsx
> 홈 및 탑 버튼 추가

- components/common/btn/HomeAndTopBtn.tsx
- components/debates/DebaterInfo.module.scss
- components/debates/DebaterInfo.tsx
- components/debates/debate/Comments.module.scss
- components/debates/debate/Comments.tsx
- components/debates/debate/EditAndDelete.tsx
- components/debates/debate/index.tsx
> 프로필 이미지 테두리 추가

- utils/queries/users.ts
- 프로필 변경 성공시 토스트 메세지 출력
- 닉네임 변경 성공 시 토스트 메세지 출력
> 유저 쿼리 수정 (성공 시 토스트 메세지 추가)

- pages/mypage/MyPage.module.scss
> 마이페이지 미디어 쿼리 추가

- pages/signin/Signin.module.scss
- pages/signin/index.tsx
> 로그인 페이지 스타일링

- pages/signin/Signin.module.scss
- pages/signin/index.tsx
- 로그인 요청 수정
- 로그인 페이지 스타일링
- 로그인 정보 미입력 시 로그인 비활성화
> 로그인 요청 수정 및 스타일링

- components/debates/DebaterInfo.tsx
- components/debates/debate/Comments.tsx
- components/debates/debateroom/index.tsx
- components/debates/debates/DebatesCards.tsx
- package-lock.json
- package.json
- utils/debates/debateroom/aws.ts
- utils/debates/debateroom/webSocket.ts
- utils/queries/debates.ts
> 녹화 영상 s3 업로드 기능 추가

- api/users.ts
- components/debates/debate/Vote.tsx
- components/debates/debate/index.tsx
- pages/signin/index.tsx
- utils/queries/hearts.ts
- utils/queries/users.ts
- utils/queries/votes.ts
> 로그인/로그아웃 시 좋아요 여부와 투표 여부 반영 문제 해결

- utils/queries/users.ts
> 토큰 만료 시 삭제

- components/common/btn/HomeAndTopBtn.tsx
- pages/_app.tsx
- 이전 페이지 저장 단순 코드 개선
- 수화 불일치 에러 해결 [[참조]](https://nextjs.org/docs/messages/react-hydration-error)
> 수화 불일치 문제 해결 및 단순 코드 개선

- components/common/btn/HomeAndTopBtn.tsx
- package-lock.json
- package.json
- pages/[debateId].tsx
- pages/_app.tsx
- pages/index.tsx
- redux/modules/scrollMain.ts
- redux/store.ts
- 새로고침 시 스크롤 복원 비활성화
- 무한 스크롤 SSR 삭제
- 목록 일부 획득 실패 문제 발생 및 스크롤 위치 기억하기 정상 작동 X
- lodash 라이브러리 설치
- 스크롤 함수 디바운스 설정
- 메인에 스크롤 위치 기억하기 적용
> 스크롤 위치 기억하기

- components/common/Error.tsx
- components/common/modal/ConfirmModal.module.scss
- components/debates/debate/index.tsx
- components/debates/debateroom/experience/index.tsx
- components/debates/debates/DebatesList.tsx
- styles/globals.scss
- types.ts
- utils/debates/debateroom/useSetRecorder.ts
- 에러 페이지의 이미지 경로가 상대 경로로 되어있어 절대 경로로 수정
- 검색 시 trim 적용
- 확인 모달 스타일 및 체험 토론 시작 메시지 수정
- 정식 토론에도 토론 영상 시간 추가
- 입장하기 조건 수정
> 소소한 문제들 수정

- components/debates/debates/DebateCard.module.scss
- components/debates/debates/DebatesCards.module.scss
- components/debates/debates/DebatesCards.tsx
> 토론 카드 목록 배치 문제 해결

- components/debates/debateroom/index.tsx
- components/debates/debates/LikeBtn.tsx
- pages/_app.tsx
- pages/debate.tsx
- utils/debates/debateroom/useSetRecorder.ts
- 토론 영상 업로드 실패 문제 해결 [[참조]](https://github.com/SuSang-YuHee/Debate-Ducks-Client/issues/140)
- 토론 게시물 URL 문제 해결 [[참조]](https://github.com/SuSang-YuHee/Debate-Ducks-Client/issues/141)
> 치명적인 문제들 해결

- components/common/Header.tsx
- components/debates/DebaterInfo.tsx
- components/debates/debate/Comments.tsx
- pages/mypage/index.tsx
외부 이미지 최적화 경로 및 이미지 로더 문제로 엑박이 떠서 임시로 외부 이미지 최적화 기능을 끔
> 이미지 엑박 문제 임시 해결
